strategy:
  matrix:
    linux:
      imageName: ubuntu-latest
    mac:
      imageName: windows-latest
    windows:
      imageName: macOS-latest
pool:
  vmImage: ubuntu-latest
steps:
  - task: InstallMATLAB@1
  - task: RunMATLABBuild@1
    inputs:
      tasks: test packageToolbox
    env:
      MLM_LICENSE_TOKEN: $(MLM_LICENSE_TOKEN)