jobs:

  - job: CompileAndTestMex
    strategy:
      matrix:
        linux:
          imageName: ubuntu-latest
        # mac:
        #   imageName: macOS-latest
        # windows:
        #   imageName: windows-latest
    pool:
      vmImage: $(imageName)
    steps:
      - task: InstallMATLAB@1
      - task: RunMATLABBuild@1
        inputs:
          tasks: mex test
        env:
          MLM_LICENSE_TOKEN: $(MLM_LICENSE_TOKEN)
      - publish: 'test-results/results.xml'
        artifact: 'test-results-$(imageName)'
      - task: CopyFiles@2
        inputs:
          SourceFolder: 'toolbox'
          Contents: '**/*.mex*'
          TargetFolder: toolbox/tmpMexFolder
      - publish: 'toolbox/tmpMexFolder'
        artifact: mex-$(imageName)

  - job: CreateAndReleaseToolbox
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: InstallMATLAB@1
      - task: DownloadPipelineArtifact@2
        inputs:
          # itemPattern: '**/*.mex*'
          itemPattern: 'mex-*'
          targetPath: 'tmpMexFolder' # https://github.com/Microsoft/azure-pipelines-tasks/issues/6739
      - task: CopyFiles@2 # Copy mex assets to correct folder
        inputs:
          SourceFolder: 'tmpMexFolder'
          Contents: '**/*.mex*'
          targetFolder: 'toolbox'
      - task: RunMATLABBuild@1
        inputs:
          tasks: packageToolbox
        env:
          MLM_LICENSE_TOKEN: $(MLM_LICENSE_TOKEN)
    dependsOn: CompileAndTestMex