version: 2.1
orbs:
  matlab: mathworks/matlab@1

executors:
  linux: # a Linux VM running Ubuntu 20.04
    machine:
      image: default
  macos: # macos executor running Xcode
    macos:
      xcode: 14.2.0
  windows:
    resource_class: "windows.medium"
    machine:
      image: default

jobs:
  compile-and-test-mex:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - checkout
      - matlab/install
      - matlab/run-build:
          tasks: mex test
      - store_artifacts:
          path: test-results/results.xml
      - persist_to_workspace:
          root: .
          paths:
            - toolbox/*.mex*
      # - store_artifacts:
      #     path: toolbox/
      #     # destination: mex-<< parameters.os>> # This is a circle CI limitation which doesn't allows us to get the dynamic names of executors

  create-and-release-toolbox:
    machine:
      image: ubuntu-2204:2024.01.1
    steps:
      - checkout
      - matlab/install
      - attach_workspace:
          at: .
      - run:
          command: |
                    cd toolbox
                    ls -la
          name: List workspace contents
      - matlab/run-build:
          tasks: packageToolbox

workflows:
  toolbox-create-package-release:
    jobs:
      - compile-and-test-mex:
          matrix:
            parameters:
              os: [linux, macos] #Removing windows for now as MATLAB install fails there
      - create-and-release-toolbox:
          requires:
            - compile-and-test-mex
