version: '2.1'
setup: true
orbs:
  path-filtering: circleci/path-filtering@0.1.7
workflows:
  generate-config:
    jobs:
      - path-filtering/filter:
          # base-revision: << pipeline.git.branch >>
          # config-path: .circleci/continue_config.yml
          mapping: |
            .* toolbox-distribution true .circleci/ToolboxDistribution.yml
      - path-filtering/filter:
          config-path: .circleci/continue_config.yml
          mapping: |
            .* toolbox-distribution true .circleci/ToolboxDistribution.yml
            .* another-workflow true
