---
version: 2
plan:
  project-key: MARS
  key: ROCKET
  name: Build the rocket
stages:
  - Build hull:
    - Build

Build:
  tasks:
    - script: |
        echo 'Hello'
        echo 'World!'

#     - com.atlassian.bamboo.plugin.dotnet:msbuild:
#       - solution: YourSolution.sln
#       - label: a
        
#     - runMATLABCommand:
#       - matlabExecutable: MATLAB R2022a
#       - matlabCommand: pwd
