---
version: 2
plan:
  project-key: MARS
  key: ROCKET
  name: Build the rocket
stages:
  - Build hull:
    - Build

Build:
  tasks:
    - script: |
        echo 'Hello'
        echo 'World!'
        
    - matlab-bamboo-plugin:runMATLABCommand:
      - matlabExecutable: MATLAB R2022a
      - matlabCommand: pwd
