# This is a basic workflow to help you get started with MATLAB Actions

name: MATLAB Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:

    # A job will run for all the OS present in the matrix
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]
    
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Sets up MATLAB on the GitHub Actions runner
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1

      - name: Build a mex file
        uses: matlab-actions/run-command@v1
        with:
          command: mex code/yprime.c

      # - name: Build a standalone application / executable
        # uses: matlab-actions/run-command@v1
        # with:
        #   command: mcc -m code/dayofyear.m
        # run: mcc -m code/dayofyear.m;
