name: MEX Setup

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:

    # A job will run for all the OS present in the matrix
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-12]
    
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Sets up MATLAB on the GitHub Actions runner
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1

      - name: Run build
        uses: matlab-actions/run-build@v1
        with:
          tasks: checkCode createMex testMex

      - name: Upload code coverage report
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage ${{ matrix.os }} ${{ matrix.release }}
          path: code-coverage/results.xml

      - name: Upload test results          
        uses: actions/upload-artifact@v3
        with:
          name: test-results ${{ matrix.os }} ${{ matrix.release }}
          path: test-results/results.xml
