name: Compile, Test and Release toolbox

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:

  compile-and-test-mex:
    # A job will run for all the OS present in the matrix
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-12]
    
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1

      - name: Run build
        uses: matlab-actions/run-build@v1
        with:
          tasks: check createMex testMex

      - name: Upload code coverage report
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage ${{ matrix.os }}
          path: code-coverage/results.xml

      - name: Upload test results          
        uses: actions/upload-artifact@v3
        with:
          name: test-results ${{ matrix.os }}
          path: test-results/results.xml

      - name: Upload mex file
        uses: actions/upload-artifact@v3
        with:
          name: mex-${{ matrix.os }}
          path: toolbox/**/*.mex*
          
  create-and-release-toolbox:
    needs: compile-and-test-mex
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1

      - name: Download mex files
        uses: actions/download-artifact@v3
        with: 
          path: toolbox    
          pattern: mex-*
          merge-multiple: true
        
      - name: Run build
        uses: matlab-actions/run-build@v1
        with:
          tasks: packageToolbox

      - name: Create new release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{secrets.GITHUB_TOKEN}}"
          automatic_release_tag: "cross-platform-toolbox"
          prerelease: false
          title: "Cross Platform - Array Product Toolbox"
          files: ./*.mltbx

      
