name: Compile, Test and Release toolbox

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  # This workflow contains two jobs called "compile-and-test-mex" and "create-and-release-toolbox"
  compile-and-test-mex:
    # A job will run for all the OS present in the matrix
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2022, macos-12]
    
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      
      # Sets up MATLAB on the GitHub Actions runner
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1

      # Runs build to verify code, create MEX file and finally run tests
      - name: Run build
        uses: matlab-actions/run-build@v1
        with:
          tasks: check createMex testMex

      # Uploads the test results, code coverage results and mex files to GitHub
      - name: Upload code coverage report
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage ${{ matrix.os }}
          path: code-coverage/results.xml

      - name: Upload test results          
        uses: actions/upload-artifact@v3
        with:
          name: test-results ${{ matrix.os }}
          path: test-results/results.xml

      - name: Upload mex file
        uses: actions/upload-artifact@v3
        with:
          name: mex-${{ matrix.os }}
          path: toolbox/**/*.mex*
          
  create-and-release-toolbox:
    # This job executes only after a successful completion of 'compile-and-test-mex' job
    needs: compile-and-test-mex
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Sets up MATLAB on the GitHub Actions runner
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1

      # Downloads all mex files uploaded to GitHub in the previous job
      - name: Download mex files
        uses: actions/download-artifact@v3
        with: 
          path: toolbox    
          pattern: mex-*
          merge-multiple: true
        
      # Packages all files in toolbox folder into a mltbx toolbox package  
      - name: Run build
        uses: matlab-actions/run-build@v1
        with:
          tasks: packageToolbox

      # The packaged toolbox is distributed as a GitHub release
      - name: Create new release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{secrets.GITHUB_TOKEN}}"
          automatic_release_tag: "cross-platform-toolbox"
          prerelease: false
          title: "Cross Platform - Array Product Toolbox"
          files: ./*.mltbx

      
