# This is a basic workflow to help you get started with MATLAB Actions

name: Build and test your tool

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Sets up MATLAB on the GitHub Actions runner
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1

      - name: Execute your buildplan
        uses: matlab-actions/run-build@v1
        with:
          tasks: clean check compile
        
      - name: Run all tests and generate artifacts
        uses: matlab-actions/run-tests@v1
        with:
          source-folder: codeDesign
          test-results-junit: test-results/results.xml
          code-coverage-cobertura: code-coverage/coverage.xml
 
      - name: Upload test results artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-restuls
          path: test-results/results.xml
 
      - name: Upload code coverage artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: code-coverage
          path: code-coverage/coverage.xml
